language: r
cache: packages
sudo: required
dist: xenial

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      
r_packages:
  - covr
  - devtools

after_success:
  - Rscript -e 'library(covr); codecov()'